spring:
  application:
   name: SQLtest
  datasource:
    url: jdbc:postgresql://localhost:5432/SQL
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
server:
  port: 8081

##logging:
##  level:
##    root: INFO
##    org.springframework: DEBUG
##    org.hibernate: DEBUG
##    org.hibernate.SQL: DEBUG
##    org.hibernate.type.descriptor.sql.BasicBinder: TRACE